-- ============================================================
--  Data.lua  |  Shared static addon lookup tables
-- ============================================================

SPEC_ICONS = {
    ["Blood"] = "Interface\\Icons\\Spell_DeathKnight_BloodPresence",
    ["Frost DK"] = "Interface\\Icons\\Spell_DeathKnight_FrostPresence",
    ["Unholy"] = "Interface\\Icons\\Spell_DeathKnight_UnholyPresence",
    ["Balance"] = "Interface\\Icons\\Spell_Nature_StarFall",
    ["Feral"] = "Interface\\Icons\\Ability_Druid_CatForm",
    ["Restoration"] = "Interface\\Icons\\Spell_Nature_HealingTouch",
    ["Beast Mastery"] = "Interface\\Icons\\Ability_Hunter_BeastTaming",
    ["Marksmanship"] = "Interface\\Icons\\Ability_Marksmanship",
    ["Survival"] = "Interface\\Icons\\Ability_Hunter_SwiftStrike",
    ["Arcane"] = "Interface\\Icons\\Spell_Holy_MagicalSentry",
    ["Fire"] = "Interface\\Icons\\Spell_Fire_FireBolt02",
    ["Frost"] = "Interface\\Icons\\Spell_Frost_FrostBolt02",
    ["Holy Pala"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
    ["Protection"] = "Interface\\Icons\\Ability_Paladin_ShieldoftheTemplar",
    ["Retribution"] = "Interface\\Icons\\Spell_Holy_AuraofLight",
    ["Discipline"] = "Interface\\Icons\\Spell_Holy_WordFortitude",
    ["Holy Priest"] = "Interface\\Icons\\Spell_Holy_GuardianSpirit",
    ["Shadow"] = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",
    ["Assassination"] = "Interface\\Icons\\Ability_Rogue_Eviscerate",
    ["Combat"] = "Interface\\Icons\\Ability_BackStab",
    ["Subtlety"] = "Interface\\Icons\\Ability_Stealth",
    ["Elemental"] = "Interface\\Icons\\Spell_Nature_Lightning",
    ["Enhancement"] = "Interface\\Icons\\Spell_Nature_LightningShield",
    ["Restoration Shaman"] = "Interface\\Icons\\Spell_Nature_MagicImmunity",
    ["Affliction"] = "Interface\\Icons\\Spell_Shadow_DeathCoil",
    ["Demonology"] = "Interface\\Icons\\Spell_Shadow_Metamorphosis",
    ["Destruction"] = "Interface\\Icons\\Spell_Shadow_RainOfFire",
    ["Arms"] = "Interface\\Icons\\Ability_Warrior_Sunder",
    ["Fury"] = "Interface\\Icons\\Ability_Warrior_InnerRage",
    ["Protection Warrior"] = "Interface\\Icons\\Ability_Warrior_DefensiveStance",
}

CLASS_SPECS = {
    ["Death Knight"] = {"Blood", "Frost DK", "Unholy"},
    ["Druid"] = {"Balance", "Feral", "Restoration"},
    ["Hunter"] = {"Beast Mastery", "Marksmanship", "Survival"},
    ["Mage"] = {"Arcane", "Fire", "Frost"},
    ["Paladin"] = {"Holy Pala", "Protection", "Retribution"},
    ["Priest"] = {"Discipline", "Holy Priest", "Shadow"},
    ["Rogue"] = {"Assassination", "Combat", "Subtlety"},
    ["Shaman"] = {"Elemental", "Enhancement", "Restoration Shaman"},
    ["Warlock"] = {"Affliction", "Demonology", "Destruction"},
    ["Warrior"] = {"Arms", "Fury", "Protection Warrior"},
}

CLASS_COLORS = {
    ["Death Knight"] = {r=0.77, g=0.12, b=0.23},
    ["Druid"] = {r=1.00, g=0.49, b=0.04},
    ["Hunter"] = {r=0.67, g=0.83, b=0.45},
    ["Mage"] = {r=0.25, g=0.78, b=0.92},
    ["Paladin"] = {r=0.96, g=0.55, b=0.73},
    ["Priest"] = {r=1.00, g=1.00, b=1.00},
    ["Rogue"] = {r=1.00, g=0.96, b=0.41},
    ["Shaman"] = {r=0.00, g=0.44, b=0.87},
    ["Warlock"] = {r=0.53, g=0.53, b=0.93},
    ["Warrior"] = {r=0.78, g=0.61, b=0.23},
}

CLASS_TABS = {"Death Knight", "Druid", "Hunter", "Mage", "Paladin", "Priest", "Rogue", "Shaman", "Warlock", "Warrior", "Raid", "All"}

TAB_LABELS = {
    ["Death Knight"] = "DK",
    ["Druid"] = "Druid",
    ["Hunter"] = "Hunter",
    ["Mage"] = "Mage",
    ["Paladin"] = "Paladin",
    ["Priest"] = "Priest",
    ["Rogue"] = "Rogue",
    ["Shaman"] = "Shaman",
    ["Warlock"] = "Warlock",
    ["Warrior"] = "Warrior",
    ["Raid"] = "Raid",
    ["All"] = "All",
}

TIER_COLORS = {
    [18] = {r=0.20, g=0.60, b=0.80},
    [1] = {r=0.70, g=0.36, b=0.00},
    [2] = {r=0.55, g=0.00, b=0.00},
    [3] = {r=0.18, g=0.49, b=0.20},
    [4] = {r=0.08, g=0.40, b=0.75},
    [5] = {r=0.42, g=0.10, b=0.54},
    [6] = {r=0.00, g=0.51, b=0.56},
    [7] = {r=0.52, g=0.42, b=0.00},
    [8] = {r=0.68, g=0.08, b=0.34},
    [9] = {r=0.33, g=0.43, b=0.48},
    [10] = {r=0.90, g=0.29, b=0.00},
    [11] = {r=0.00, g=0.41, b=0.36},
    [12] = {r=0.16, g=0.21, b=0.58},
    [13] = {r=0.34, g=0.55, b=0.18},
    [14] = {r=0.29, g=0.08, b=0.55},
    [15] = {r=0.00, g=0.38, b=0.39},
    [16] = {r=0.53, g=0.06, b=0.31},
    [17] = {r=0.11, g=0.37, b=0.13},
}

TIER_LABELS = {
    [0] = "T0 — 5-Man Dungeons",
    [1] = "T1 — Molten Core & Onyxia",
    [2] = "T2 — Blackwing Lair",
    [3] = "T3 — Pre-AQ / Zul'Gurub",
    [4] = "T4 — AQ War",
    [5] = "T5 — Anh'Qiraj",
    [6] = "T6 — Naxxramas (Kel'Thuzad)",
    [7] = "T7 — Pre-TBC",
    [8] = "T8 — Karazhan / Gruul / Mag",
    [9] = "T9 — SSC & Tempest Keep",
    [10] = "T10 — Hyjal & Black Temple",
    [11] = "T11 — Zul'Aman",
    [12] = "T12 — Sunwell Plateau",
    [13] = "T13 — Naxx / EoE / OS",
    [14] = "T14 — Ulduar",
    [15] = "T15 — Trial of the Crusader",
    [16] = "T16 — Icecrown Citadel",
    [17] = "T17 — Ruby Sanctum",
}

ROLE_DEFS = {
    {key="TNK", label="Tank", color={r=0.20, g=0.60, b=1.00}, icon="Interface\\Icons\\Ability_Warrior_DefensiveStance"},
    {key="HLR", label="Healer", color={r=0.20, g=1.00, b=0.40}, icon="Interface\\Icons\\Spell_ChargePositive"},
    {key="DPS", label="DPS", color={r=1.00, g=0.40, b=0.20}, icon="Interface\\Icons\\Ability_DualWield"},
}

ROLE_BY_KEY = {}
for _, roleDef in ipairs(ROLE_DEFS) do ROLE_BY_KEY[roleDef.key] = roleDef end

RAID_ABBR = {
    ["Molten Core"] = "MC",
    ["Onyxia's Lair"] = "Ony",
    ["Blackwing Lair"] = "BWL",
    ["Zul'Gurub"] = "ZG",
    ["Ruins of Ahn'Qiraj"] = "AQ20",
    ["Ahn'Qiraj (AQ40)"] = "AQ40",
    ["Ahn'Qiraj (AQ20)"] = "AQ20",
    ["Naxxramas (Classic)"] = "Naxx60",
    ["Karazhan"] = "Kara",
    ["Gruul's Lair"] = "Gruul",
    ["Magtheridon's Lair"] = "Mag",
    ["Serpentshrine Cavern"] = "SSC",
    ["Tempest Keep"] = "TK",
    ["Mount Hyjal"] = "Hyjal",
    ["Black Temple"] = "BT",
    ["Zul'Aman"] = "ZA",
    ["Sunwell Plateau"] = "SW",
    ["Naxxramas 10"] = "Naxx10",
    ["Naxxramas 25"] = "Naxx25",
    ["Eye of Eternity 10"] = "EoE10",
    ["Eye of Eternity 25"] = "EoE25",
    ["Obsidian Sanctum 10"] = "OS10",
    ["Obsidian Sanctum 25"] = "OS25",
    ["Ulduar 10"] = "Uld10",
    ["Ulduar 25"] = "Uld25",
    ["Trial of the Crusader 10"] = "ToC10",
    ["Trial of the Crusader 25"] = "ToC25",
    ["Trial of the Grand Crusader 10"] = "ToGC10",
    ["Trial of the Grand Crusader 25"] = "ToGC25",
    ["Icecrown Citadel 10"] = "ICC10",
    ["Icecrown Citadel 25"] = "ICC25",
    ["ICC 10 Heroic"] = "ICC10H",
    ["ICC 25 Heroic"] = "ICC25H",
    ["Ruby Sanctum 10"] = "RS10",
    ["Ruby Sanctum 25"] = "RS25",
    ["N/A (5-Man)"] = "5-Man",
}

CLASS_ICONS = {
    ["Death Knight"] = "Interface\\Icons\\Spell_DeathKnight_ClassIcon",
    ["Druid"] = "Interface\\Icons\\Ability_Druid_Maul",
    ["Hunter"] = "Interface\\Icons\\INV_Weapon_Bow_07",
    ["Mage"] = "Interface\\Icons\\INV_Staff_13",
    ["Paladin"] = "Interface\\Icons\\Spell_Holy_HolyBolt",
    ["Priest"] = "Interface\\Icons\\INV_Staff_30",
    ["Rogue"] = "Interface\\Icons\\Ability_Stealth",
    ["Shaman"] = "Interface\\Icons\\Spell_Nature_BloodLust",
    ["Warlock"] = "Interface\\Icons\\Spell_Nature_FaerieFire",
    ["Warrior"] = "Interface\\Icons\\Ability_Warrior_BattleShout",
}